import DetailMv from '@/components/element/DetailMv'
import Footer from '@/components/layout/Footer'
import MessageFromCEO from '@/components/section/about/MessageFromCEO'
import Mission from '@/components/section/about/Mission'
import OurLogo from '@/components/section/common/OurLogo'
import OurUniform from '@/components/section/about/OurUniform'
import Philosophy from '@/components/section/about/Philosophy'
import Access from '@/components/section/common/Access'
import Contact from '@/components/section/common/Contact'
import Head from 'next/head'
import React from 'react'
import styles from '@/styles/pages/About.module.scss'
import Header from '@/components/layout/Header'
import CompanyOverview from '@/components/section/about/CompanyOverview'
import { motion } from 'framer-motion'

function About() {
  return (
    <>
        <Head>
            <title>About | Aarth Security</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <Header />
        <motion.div
          className='box'
          initial={{ clipPath: "inset(0 0% 0 0%)" }} // 初期状態
          animate={{ clipPath: 'inset(0 0 0 100%)' }} // マウント時
          transition={{ delay:.5, duration: .4, ease: 'easeInOut' }} // アニメーションの設定
          exit={{ clipPath: "inset(0 0% 0 0%)" }}    // アンマウント時
        ></motion.div>
        <div className={styles.container}>
            <main>
                <DetailMv en='About Us' ja='私たちについて' />
                <Mission />
                <Philosophy />
                <MessageFromCEO />
                <OurUniform />
                <OurLogo />
                <CompanyOverview />
                <Contact />
                <Access />
                <Footer />
            </main>
        </div>
    </>
  )
}

export default About
