import React from 'react'
import styles from '@/styles/pages/Recruit.module.scss'
import Head from 'next/head'
import DetailMv from '@/components/element/DetailMv'
import Contact from '@/components/section/common/Contact'
import Access from '@/components/section/common/Access'
import Footer from '@/components/layout/Footer'
import WeReLookingFor from '@/components/section/recruit/WeReLookingFor'
import OurLogo from '@/components/section/common/OurLogo'
import Header from '@/components/layout/Header'
import { motion } from 'framer-motion'

function Recruit() {
  return (
    <>
        <Head>
            <title>Recruit | Aarth Security</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <Header />
        <motion.div
          className='box'
          initial={{ clipPath: "inset(0 0% 0 0%)" }} // 初期状態
          animate={{ clipPath: 'inset(0 0 0 100%)' }} // マウント時
          transition={{ delay:.5, duration: .4, ease: 'easeInOut' }} // アニメーションの設定
          exit={{ clipPath: "inset(0 0% 0 0%)" }}    // アンマウント時
          onAnimationStart={() => document.body.style.overflow = 'hidden'}
          onAnimationComplete={() => document.body.style.overflow = 'auto'}
        ></motion.div>
        <div className={styles.container}>
            <main>
                <DetailMv en='Recruit' ja='採用情報' />
                <WeReLookingFor />
                <OurLogo />
                <Contact />
                <Access />
                <Footer />
            </main>
        </div>
    </>
  )
}

export default Recruit
