import React from 'react'
import styles from '@/styles/pages/Recruit.module.scss'
import Head from 'next/head'
import DetailMv from '@/components/element/DetailMv'
import Contact from '@/components/section/common/Contact'
import Access from '@/components/section/common/Access'
import Footer from '@/components/layout/Footer'
import WeReLookingFor from '@/components/section/recruit/WeReLookingFor'
import OurLogo from '@/components/section/common/OurLogo'
import Header from '@/components/layout/Header'

function Recruit() {
  return (
    <>
        <Head>
            <title>Recruit | Aarth Security</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <Header />
        <div className={styles.container}>
            <main>
                <DetailMv en='Recruit' ja='採用情報' />
                <WeReLookingFor />
                <OurLogo />
                <Contact />
                <Access />
                <Footer />
            </main>
        </div>
    </>
  )
}

export default Recruit
