import DetailMv from '@/components/element/DetailMv'
import Footer from '@/components/layout/Footer'
import Access from '@/components/section/common/Access'
import Contact from '@/components/section/common/Contact'
import Head from 'next/head'
import React, { useState } from 'react'
import styles from '@/styles/pages/Service.module.scss'
import Tab from '@/components/section/service/Tab'
import Content from '@/components/section/service/Content'

function Service() {
  const [currentTab, setCurrentTab] = useState(1)
  return (
    <>
        <Head>
            <title>Service | Aarth Security</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <div className={styles.container}>
            <main>
                <DetailMv en='Service' ja='サービス内容' />
                <Tab currentTab={currentTab} setCurrentTab={setCurrentTab} />
                <Content currentTab={currentTab} />
                <Contact />
                <Access />
                <Footer />
            </main>
        </div>
    </>
  )
}

export default Service
