import Head from "next/head";
import styles from "@/styles/pages/Top.module.scss";
import Mv from "@/components/section/top/Mv";
import About from "@/components/section/top/About";
import Service from "@/components/section/top/Service";
import Recruit from "@/components/section/top/Recruit";
import News from "@/components/section/top/News";
import Contact from "@/components/section/common/Contact";
import Access from "@/components/section/common/Access";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import { motion } from 'framer-motion'

export default function Home() {
  return (
    <>
        <Head>
          <meta name="viewport" content="width=device-width,initial-scale=1"/>
          <title>Aarth Security | 安全と安心を、先導します。</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="keywords" content=""/>
          <meta property="og:type" content="website"/>
          <meta property="og:title" content="FLARUNÉ |  ALBION Singapore"/>
          <meta property="og:description" content="Japanese-indigo extract enhances the skin’s self soothing power, for vibrant and clean skin. Find out more on ALBION Singapore website."/>
          {/* <meta property="og:url" content="http://www.albion-cosmetics.com/seasonal/flarune/sg/index.html"/> */}
        </Head>
        
        <motion.div
          className='box'
          initial={{ clipPath: "inset(0 0% 0 0%)" }} // 初期状態
          animate={{ clipPath: 'inset(0 0 0 100%)' }} // マウント時
          transition={{ duration: .6, ease: 'easeInOut' }} // アニメーションの設定
          exit={{ clipPath: "inset(0 0% 0 0%)" }}    // アンマウント時
          onAnimationStart={() => document.body.style.overflow = 'hidden'}
          onAnimationComplete={() => document.body.style.overflow = 'auto'}
        ></motion.div>
        <Header />
        <div className={styles.container}>
          <main>
            <Mv />
            <About />
            <Service />
            <Recruit />
            <News />
            <Contact />
            <Access />
          </main>
        </div>
        <Footer></Footer>
    </>
  );
}
